version: '3.8'

services:

  es-node-1:
    image: elasticsearch:7.8.0
    container_name: es-node-1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es-node-1/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/plugins/analysis-ik:/usr/share/elasticsearch/plugins/analysis-ik
      - ./elasticsearch/es-node-1/data:/usr/share/elasticsearch/data
      - ./elasticsearch/es-node-1/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    networks:
      - es78net

  es-node-2:
    image: elasticsearch:7.8.0
    container_name: es-node-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es-node-2/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/plugins/analysis-ik:/usr/share/elasticsearch/plugins/analysis-ik
      - ./elasticsearch/es-node-2/data:/usr/share/elasticsearch/data
      - ./elasticsearch/es-node-2/logs:/usr/share/elasticsearch/logs
    networks:
      - es78net

  es-node-3:
    image: elasticsearch:7.8.0
    container_name: es-node-3
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es-node-3/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/plugins/analysis-ik:/usr/share/elasticsearch/plugins/analysis-ik
      - ./elasticsearch/es-node-3/data:/usr/share/elasticsearch/data
      - ./elasticsearch/es-node-3/logs:/usr/share/elasticsearch/logs
    networks:
      - es78net

  kibana:
    image: kibana:7.8.0
    container_name: kibana78
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - es78net

  cerebro:
    image: lmenezes/cerebro:0.9.2
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://es-node-1:9200
    networks:
      - es78net

  logstash:
    image: logstash:7.8.0
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - es78net

networks:
  es78net:
    driver: bridge