server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://es-node-1:9200","http://es-node-2:9200","http://es-node-3:9200" ]
monitoring.ui.container.elasticsearch.enabled: true
i18n.locale: "zh-CN"
